export const ingredientsAdd = [
    {
        "_id": "643d69a5c3f7b9001cfa093c",
        "name": "Краторная булка N-200i",
        "type": "bun",
        "proteins": 80,
        "fat": 24,
        "carbohydrates": 53,
        "calories": 420,
        "price": 1255,
        "image": "https://code.s3.yandex.net/react/code/bun-02.png",
        "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
        "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
        "__v": 0
    },
    {
        "_id": "643d69a5c3f7b9001cfa0941",
        "name": "Биокотлета из марсианской Магнолии",
        "type": "main",
        "proteins": 420,
        "fat": 142,
        "carbohydrates": 242,
        "calories": 4242,
        "price": 424,
        "image": "https://code.s3.yandex.net/react/code/meat-01.png",
        "image_mobile": "https://code.s3.yandex.net/react/code/meat-01-mobile.png",
        "image_large": "https://code.s3.yandex.net/react/code/meat-01-large.png",
        "__v": 0
    },
    {
        "_id": "643d69a5c3f7b9001cfa093d",
        "name": "Флюоресцентная булка R2-D3",
        "type": "bun",
        "proteins": 44,
        "fat": 26,
        "carbohydrates": 85,
        "calories": 643,
        "price": 988,
        "image": "https://code.s3.yandex.net/react/code/bun-01.png",
        "image_mobile": "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
        "image_large": "https://code.s3.yandex.net/react/code/bun-01-large.png",
        "__v": 0
    },
    {
        "_id": "643d69a5c3f7b9001cfa0944",
        "name": "Соус традиционный галактический",
        "type": "sauce",
        "proteins": 42,
        "fat": 24,
        "carbohydrates": 42,
        "calories": 99,
        "price": 15,
        "image": "https://code.s3.yandex.net/react/code/sauce-03.png",
        "image_mobile": "https://code.s3.yandex.net/react/code/sauce-03-mobile.png",
        "image_large": "https://code.s3.yandex.net/react/code/sauce-03-large.png",
        "__v": 0
    },
    {
        "_id": "643d69a5c3f7b9001cfa0946",
        "name": "Хрустящие минеральные кольца",
        "type": "main",
        "proteins": 808,
        "fat": 689,
        "carbohydrates": 609,
        "calories": 986,
        "price": 300,
        "image": "https://code.s3.yandex.net/react/code/mineral_rings.png",
        "image_mobile": "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
        "image_large": "https://code.s3.yandex.net/react/code/mineral_rings-large.png",
        "__v": 0
    },
    {
        "_id": "643d69a5c3f7b9001cfa0947",
        "name": "Плоды Фалленианского дерева",
        "type": "main",
        "proteins": 20,
        "fat": 5,
        "carbohydrates": 55,
        "calories": 77,
        "price": 874,
        "image": "https://code.s3.yandex.net/react/code/sp_1.png",
        "image_mobile": "https://code.s3.yandex.net/react/code/sp_1-mobile.png",
        "image_large": "https://code.s3.yandex.net/react/code/sp_1-large.png",
        "__v": 0
    }
]

/*export const ingredientsDelete = [
    {
        "id": "2",
        "_id": "643d69a5c3f7b9001cfa0941",
        "name": "Биокотлета из марсианской Магнолии",
        "type": "main",
        "proteins": 420,
        "fat": 142,
        "carbohydrates": 242,
        "calories": 4242,
        "price": 424,
        "image": "https://code.s3.yandex.net/react/code/meat-01.png",
        "image_mobile": "https://code.s3.yandex.net/react/code/meat-01-mobile.png",
        "image_large": "https://code.s3.yandex.net/react/code/meat-01-large.png",
        "__v": 0
    },
    {
        "id": "4",
        "_id": "643d69a5c3f7b9001cfa0944",
        "name": "Соус традиционный галактический",
        "type": "sauce",
        "proteins": 42,
        "fat": 24,
        "carbohydrates": 42,
        "calories": 99,
        "price": 15,
        "image": "https://code.s3.yandex.net/react/code/sauce-03.png",
        "image_mobile": "https://code.s3.yandex.net/react/code/sauce-03-mobile.png",
        "image_large": "https://code.s3.yandex.net/react/code/sauce-03-large.png",
        "__v": 0
    },
    {
        "id": "5",
        "_id": "643d69a5c3f7b9001cfa0946",
        "name": "Хрустящие минеральные кольца",
        "type": "main",
        "proteins": 808,
        "fat": 689,
        "carbohydrates": 609,
        "calories": 986,
        "price": 300,
        "image": "https://code.s3.yandex.net/react/code/mineral_rings.png",
        "image_mobile": "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
        "image_large": "https://code.s3.yandex.net/react/code/mineral_rings-large.png",
        "__v": 0
    },
    {
        "id": "6",
        "_id": "643d69a5c3f7b9001cfa0947",
        "name": "Плоды Фалленианского дерева",
        "type": "main",
        "proteins": 20,
        "fat": 5,
        "carbohydrates": 55,
        "calories": 77,
        "price": 874,
        "image": "https://code.s3.yandex.net/react/code/sp_1.png",
        "image_mobile": "https://code.s3.yandex.net/react/code/sp_1-mobile.png",
        "image_large": "https://code.s3.yandex.net/react/code/sp_1-large.png",
        "__v": 0
    }

]*/
